### PR TITLE
WIP new sidebar for docs

### PR DESCRIPTION
**Pull request by ngrayluna**
## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

Adds and organizes title of new W&B product offerings to the Dev Guide.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here: https://wandb.atlassian.net/browse/DOCS-761?atlOrigin=eyJpIjoiMDk0MmQ0NTBjZjdiNDY4MWIxNDM5ZmNlMmYwZWUzMmEiLCJwIjoiaiJ9

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by ngrayluna** [comment]
Preview:

Screen Shot 2023-09-12 at 10 30 33 AM

**Comment by ngrayluna** [comment]
Next to do, add a landing page for W&B Models and W&B Platform.

**Comment by cvphelps** [comment]
@ngrayluna could Prompts go above platform please

**Comment by ngrayluna** [comment]
Screen Shot 2023-09-13 at 4 31 09 PM

Changes:
* Moved Prompts up
* Renamed Models chapter -> Model Registry
* Added redirects for this change.
* Renamed w&B_models -> models.md

**Pull request merged**
