### PR TITLE
Translation to Japanese V2.0

### PR DESCRIPTION
**Pull request by tcapelle**
New Japanese Docs V2.0
- Using `gpt-4o`
- New validation
- LLM as judge
[Weave dashboard](https://wandb.ai/capecape/gpt-translate/weave/calls?filter=%7B%22opVersionRefs%22%3A%5B%22weave%3A%2F%2F%2Fcapecape%2Fgpt-translate%2Fop%2F_translate_file%3AzYnkWNzDop5Hp7BVJD6ufPWkfWoYYUmKOaazrzZY7Lk%22%5D%2C%22parentId%22%3A%22cb31894a-5039-4b9d-a3a1-091af4acefa2%22%7D)!

### CODE REVIEW

**Comment by tcapelle** [comment]
@as_wandb @si-wandb can you take a look?

**Comment by tcapelle** [comment]
Can you take a look @ngrayluna to see if I am not butchering the docodile?

**Comment by ngrayluna** [comment]
It seems mostly fine...one thing to add is that we don't have a script that copies, update images.  i.e. We are missing some images that have been added to English docs so the translated docs reference them, but don't exist.
Screen Shot 2024-06-17 at 9 05 06 AM

**Comment by tcapelle** [comment]
This is ready for review, pushed the images in /static (we should use git lfs for this types of byte files)

**Comment by tcapelle** [comment]
cc @ngrayluna

**Comment by ngrayluna** [comment]
ChatGPT does not like [Tabs](https://docusaurus.io/docs/markdown-features/tabs), let's fix that. Essentially, tell ChatGPT to:
1. Preserve the open and closing `<Tabs>` and `<TabItem value="text">`:
```
<Tabs
  defaultValue="apple"
  values={[
    {label: 'Apple', value: 'apple'},
    {label: 'Orange', value: 'orange'},
    {label: 'Banana', value: 'banana'},
  ]}>
  <TabItem value="apple">This is an apple 🍎</TabItem>
  <TabItem value="orange">This is an orange 🍊</TabItem>
  <TabItem value="banana">This is a banana 🍌</TabItem>
</Tabs>
```

2. Within each `<TabItem value>` keep the EXACT spacing and indentation between, before, and after text that is in the original markdown.


Here are the 9 pages breaking where this is breaking the docs:

/guides/artifacts/project-scoped-automations.md
/guides/hosting/iam/ldap.md
/guides/hosting/iam/sso.md
/guides/integrations/dagster.md
/guides/integrations/lightning.md
/guides/model_registry/automation.md
/guides/model_registry/link-model-version.md
/guides/reports/create-a-report.md
/guides/track/log/media.md

**Comment by tcapelle** [comment]
Just checking some manually, they don't seem any different than the source docs? For instance iam/sso.md:
image
image
image

Not saying is not broken, just trying  to understand. Maybe removing the comments makes some difference?

Ok, some of them are incomplete. Like the `/guides/artifacts/project-scoped-automations.md`

**Comment by tcapelle** [comment]
Weave to the rescue, some completitions are "incomplete" due to length
image

**Comment by tcapelle** [comment]
Probably all this files are bad: 
image

**Comment by ngrayluna** [comment]
This a dumb question, are these translations done on the latest changes in main? 😬

Re: I did some spot checking and we are missing some stuff/is out of date by a 2-3 weeks?: 

1. The `sidebar.js` is not updated. The sidebar structure of the english docs changed a lot.
2. [We added a registry chapter](https://github.com/wandb/docodile/tree/main/docs/guides/registry)
3. [Added an Automations chapter](https://github.com/wandb/docodile/tree/main/docs/guides/automations)
4. [The Hosting chapter is out of sync](https://github.com/wandb/docodile/tree/main/docs/guides/hosting)
5. Looks like the API Reference guide is also out of date? We are currently on version 17.3 (The japanese docs has 17.1)

**Comment by tcapelle** [comment]
I merged master multiple times, but didn't re do everything. I will manually translate these...

**Comment by tcapelle** [comment]
I think that for the sake of completeness, I will commit the reference `docs_en` used for this translation.

**Comment by tcapelle** [comment]
we should be ok now
```
git -C docs/ref  diff --name-only --diff-filter=AM $(git -C docs/ref/  rev-list -n 1 --before="2 weeks ago" HEAD)..HEAD >> ref.txt
``` 
is your friend =)

**Review by ngrayluna — APPROVED** [review]

**Pull request merged**
