### PR TITLE
Reports: Updated import statement. Removed mention of beta

### PR DESCRIPTION
**Pull request by ngrayluna**
## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

https://wandb.atlassian.net/browse/DOCS-875

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by ngrayluna** [comment]
I removed the link to the colab because it doesn't show the new import statements. Is there a new one to refer to?

**Comment by sephmard** [comment]
We shouldnt remove the colab but should update the code within the existing one. @andrewtruong can help.

**Comment by ngrayluna** [comment]
Correction: I thought I removed the colab, it's still there.

**Comment by ngrayluna** [comment]
@sephmard Should I hold off merging and deploying until Andrew updates the colab?

**Comment by sephmard** [comment]
If it is still there then lets merge. And start a slack thread with andrew to give us edit permission on the colab

**Pull request merged**
