### PR TITLE
Edits to the tutorials documentation and quickstart

### PR DESCRIPTION
**Pull request by cvphelps**
Reacting to the edits made in this PR https://github.com/wandb/docodile/pull/221 

1. Update the tutorials home page
2. Update sidebar, page naming, and links to be more direct and less verbose

## WIP screenshot

image

### CODE REVIEW

**Comment by ngrayluna** [comment]
Formatting to do: go through code snippets innotebooks and try to get them under the 75 character line max. Re: we got feedback from Lukas that scrolling to see remaining code was infuriating.

**Comment by ngrayluna** [comment]
To do: @scottire @tcapelle  Add info about requirements, how to generate the tutorial markdown file.

**Comment by tcapelle** [comment]
Probably we need to replace the "baked" images in binary on that MD file by the actual references.

**Comment by ngrayluna** [comment]
> Probably we need to replace the "baked" images in binary on that MD file by the actual references.

Agreed. We'll need to fix that before merging.

**Comment by ngrayluna** [comment]
Circling in on this, some links are broken: 

```
 - On source page path = /tutorials/artifacts:
   -> linking to Model_Registry_E2E (resolved as: /tutorials/Model_Registry_E2E)

- On source page path = /tutorials/experiments:
   -> linking to W&B_Tables_Quickstart.md (resolved as: /tutorials/W&B_Tables_Quickstart.md)

- On source page path = /tutorials/sweeps:
   -> linking to Pipeline_Versioning_with_W&B_Artifacts (resolved as: /tutorials/Pipeline_Versioning_with_W&B_Artifacts)

- On source page path = /tutorials/tables:
   -> linking to Organizing_Hyperparameter_Sweeps_in_PyTorch_with_W&B (resolved as: /tutorials/Organizing_Hyperparameter_Sweeps_in_PyTorch_with_W&B)```

**Comment by cvphelps** [comment]
@ngrayluna thank you! taking a look now to fix these links

**Comment by cvphelps** [comment]
PR ready to go — [slack thread](https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1684454277946039?thread_ts=1683930129.825779&cid=C01DX8LRZEJ)

**Pull request merged**
