### PR TITLE
[DO NOT MERGE] Add Docs for the HuggingFace Autologger

### PR DESCRIPTION
**Pull request by ash0ts**
## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by ash0ts** [comment]
Similar to @morganmcg1, the Japanese docs are failing to build. Any ideas @ngrayluna?

**Comment by ngrayluna** [comment]
Fixed. We have this weird rule right now were we need to have a 1:1 file structure w/ the japanese docs.  (we're working on improving this).

**Comment by ngrayluna** [comment]
Oddly enough, the doc build is working for me and for the automated GH action. So it might be that your local set up is somehow messing the doc build (This is happening to more than one person so yeah, go figure).

**Comment by ngrayluna** [comment]
@ash0ts Is this ready for PR review? (This is in draft mode).

**Comment by ash0ts** [comment]
Hey @ngrayluna! We are currently blocked on product functionality to release these autologgers formally so we can keep this in the draft state. Note we may remove this PR if we find that we will not promote these workflows

**Comment by ngrayluna** [comment]
Noted. Thanks!

**Comment by ngrayluna** [comment]
@ash0ts Closing this PR. Feel free to open when this is no longer blocked. :)

**Pull request closed without merging**
