### PR TITLE
Add metrics

### PR DESCRIPTION
**Pull request by ngrayluna**
## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

Add _all_ the Python backen metrics to our docs page.

## Ticket

https://wandb.atlassian.net/browse/DOCS-766?atlOrigin=eyJpIjoiYzU0OTczMWVlYmVhNDQ2Njg2MGMyYTQ0Yjg5MGM1NTIiLCJwIjoiaiJ9

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by ngrayluna** [comment]
QQ: @dmitryduev I didn't add the name of the Python Classes this round. I can add them and/or do that as a fast follow. Up to ya

**Review by dmitryduev — APPROVED** [review]
This is wonderful, thanks a ton @ngrayluna!! Those names  are not python class names, but rather the tags that we assign to those metrics. Now that they are exposed in the Run object (albeit under a private attribute _system_metrics), I think it would make sense to have the names here. Maybe under expandable blocks before/after the computation details for each metric? Or in a separate summary section in a table at the end of the document?

**Comment by dmitryduev** [comment]
@ngrayluna what are your thoughts about the last two sections of my notion doc (configuration + using in the user process)? It's very useful, albeit referred to as WIP bc it's all under private attributes...

**Comment by ngrayluna** [comment]
@dmitryduev  Added tags :)

Re: How about a follow up PR for last two sections when we feel it's no longer a WIP? :)?

**Pull request merged**
