### PR TITLE
Add SCIM roles API endpoints and mention SCIM API support for SaaS Cloud

### PR DESCRIPTION
**Pull request by abhinavg6**
## Description

Add the SCIM Roles API endpoints and mention the SCIM API support for SaaS Cloud. Also indicate the need for basic authentication when authenticating to the SCIM API.

## Ticket

NA

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings. - Still getting the TypeError: Invalid URL error
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by abhinavg6** [comment]
@ngrayluna - If you review this, request to please check with me before making any vale fixes. Some suggestions are non relevant here. E.g. we don't want to unfurl SCIM at every place as it has already been done at start of the SCIM doc, or we don't want to properly capitalize the API endpoint headers - those are meant to be all caps. And so on. Some things can change the intended meaning, which I want to avoid. So please check with me if you make any edits. Thank you.

**Comment by ngrayluna** [comment]
@abhinavg6 I added "SCIM" to our allow list. It won't show up in our Vale checks anymore :)

**Review by adityachoudhari26 — APPROVED** [review]
LGTM

**Comment by abhinavg6** [comment]
> @abhinavg6 I added "SCIM" to our allow list. It won't show up in our Vale checks anymore :)

Thanks @ngrayluna . I've made a few more vale fixes but my english language and word tuning skills end here. Following suggestions need to be ignored or maybe added to the allowlist as well:

- Use 'administrator' instead of 'admin'. -- We use the word "admin" to refer to the admin role, so it's legit.
- 'Custom role SCIM API' should use sentence-style capitalization. -- I can't use lowercase for SCIM and API as those are meant to be caps
- Did you really mean 'inheritedFrom'? -- This is the actual name of the field in our API
- Spell out 'PATCH', if it's unfamiliar to the audience. -- This is the actual HTTP verb and is specified in caps at most places
- Spell out 'PUT', if it's unfamiliar to the audience. -- -- This is the actual HTTP verb and is specified in caps at most places

Could we please approve this before tomorrow's release? Thanks.

**Review by ngrayluna — APPROVED** [review]

**Comment by ngrayluna** [comment]
@abhinavg6 Thanks for flagging. We'll ignore Vale's response for now. It might be useful to have those warnings in the future. We'll keep on eye on it. 

I did some minor word smithing. Aside from that. Looks good to merge. Merge when ready.

**Comment by abhinavg6** [comment]
Thanks Noah, appreciate it. Merging now.

**Pull request merged**
