### PR TITLE
Adds new integrations docs page for Hugging Face Accelerate

### PR DESCRIPTION
**Pull request by morganmcg1**
## Description
Adds a new Integrations docs page for [Hugging Face Accelerate](https://huggingface.co/docs/accelerate/main/en/usage_guides/tracking)

## Checklist
Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply. 

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Review by ngrayluna — APPROVED** [review]
Nice! QQ: On the left sidebar, do you want Hugging Face Accelerate after "Add wandb to any library" or before Hugging Face Transformers page? (To keep it in semi alphabetical order).

**Comment by morganmcg1** [comment]
lol sorry I was thinking "Accelerate" when I added the position, I'll move it down below Transformers

**Comment by morganmcg1** [comment]
Ok sidebar fixed, made some additional small formatting changes and code explanations

**Comment by ngrayluna** [comment]
Lol. All good. I did the same with PyTorch and PyTorch lightning docs.

**Pull request merged**
