### PR TITLE
added back requeuing section

### PR DESCRIPTION
**Pull request by tristan-spaulding2**
## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by tristan-spaulding2** [comment]
@ngrayluna adding this back.  BTW the .ja docs hit this error again but everything else works. 
ERROR in ./i18n/ja/docusaurus-plugin-content-docs/current/quickstart.md

**Comment by ngrayluna** [comment]
Thanks for re-adding this Tristan! It was lost in the great snap. 

Starting a thread here @KyleGoyette @tristan-spaulding2 to discuss where automatic run re-queuing content should go. 

Currently it is listed for here: https://docs.wandb.ai/guides/launch/launch-view-jobs

Possible alternatives:
* [FAQ](https://docs.wandb.ai/guides/launch/launch-faqs)? 
* [Set up Kubernetes page](https://docs.wandb.ai/guides/launch/setup-launch-kubernetes)
* ?

**Comment by tristan-spaulding2** [comment]
yeah I put it here because we do want to support it for other than just Kubernetes "soon" (3 - 6 months), and it seems more core than a FAQ.  But I agree it's debatable.

**Comment by cvphelps** [comment]
@ngrayluna could you please merge and deploy this on Thursday afternoon

**Comment by ngrayluna** [comment]
@KyleGoyette @tristan-spaulding2  Can we move this to the FAQ for now?

**Comment by KyleGoyette** [comment]
Yes lets put it in FAQ for now

**Pull request merged**
