### PR TITLE
Adding mention of SCIM role assignment API

### PR DESCRIPTION
**Pull request by abhinavg6**
## Description

Adds the mention of new SCIM role assignment API

## Ticket

NA

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings. - Still getting the TypeError: Invalid URL
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by abhinavg6** [comment]
Please don't review & merge yet. I'll tag the docs team once it's ready for review. Thanks.

**Review by ngrayluna — APPROVED** [review]

**Comment by ngrayluna** [comment]
Ooops. Sorry. I approved it before seeing your note.  Converted it to a draft for now.

**Comment by abhinavg6** [comment]
@ngrayluna - We're now ready to merge this PR. I've made a last set of changes today to incorporate latest product changes. Given you had earlier reviewed it and there are still no other Vale issues (other than HTTP PATCH noise), is it ok for me to merge? I would like to get it out with tomorrow's release. Thanks.
cc @adityachoudhari26

**Comment by ngrayluna** [comment]
Thanks for the update @abhinavg6 ! Merged. Changes will go out today around noon PST.

**Pull request merged**
