### PR TITLE
New Korean Translation [Do not merge]

### PR DESCRIPTION
**Pull request by tcapelle**
- New dict
- Enforce dict usage on prompt

### CODE REVIEW

**Comment by tcapelle** [comment]
Wow, good work @si-wandb !
I am impressed that it still translated wrong words like Artifacts...

**Comment by si-wandb** [comment]
Thanks @tcapelle! 
Yeah I know... I was surprised to see that. Had to make a lot of edits like that

**Comment by tcapelle** [comment]
Don't Delete @ngrayluna , we need to capture @si-wandb changes to improve our prompting 💪

**Comment by ngrayluna** [comment]
@thanos-wandb You can merge this into ko-eng if ya want. 🤷

**Comment by tcapelle** [comment]
nono, don't merge

**Review by ngrayluna — APPROVED** [review]

**Comment by ngrayluna** [comment]
Lol noted

**Comment by johndmulhausen** [comment]
Closing as stale

**Pull request closed without merging**
