### PR TITLE
reorg docs (pretty URLS, no docs subdir, redirs!)

### PR DESCRIPTION
**Pull request by raubitsj**
Massive reorg of docs.

1)
Urls that were:
http://docs.wandb.com/docs/frameworks/keras.html
are now:
http://docs.wandb.com/frameworks/keras

2)
All files have file "redirects" to the new name

3)
Removed any unlinked files and make the redirs to appropriate new files

4)
directories now have redirects so you can link to:
http://docs.wandb.com/frameworks
which will redirect to
http://docs.wandb.com/frameworks/keras

### CODE REVIEW

**Comment by raubitsj** [comment]
I can host a running yarn instance tomorrow if you want to verify things.

**Comment by shawnlewis** [comment]
This is cool :)

**Comment by vanpelt** [comment]
This is SICK!

**Comment by nbardy** [comment]
Fantastic Jeff, great job on the backwards compatibility

**Pull request merged**
