### PR TITLE
add llama_index documentation

### PR DESCRIPTION
**Pull request by ayulockin**
## Description

This PR adds a section in the Prompts section of our documentation to add an upcoming integration with LlamaIndex. 

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
     This was failing for Japanese docs imo. Not sure how to approach.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

### CODE REVIEW

**Comment by ngrayluna** [comment]
Interesting. I checked out your branch and the build works locally....you're working off of main, yes?

Can you try:
```
cd docodile
yarn install

yarn docusaurus build --locale en
```
if that works, then:

```python
yarn docusaurus build --locale ja
```

**Comment by ayulockin** [comment]
Hey @ngrayluna,

`yarn docusaurus build --locale en` this works. Build is successful.

`yarn docusaurus build --locale ja` getting this error:

image

**Comment by ngrayluna** [comment]
@ayulockin What version of docusarus do you have?

**Comment by ayulockin** [comment]
Hey @ngrayluna this PR is ready to be merged.

**Review by ngrayluna — APPROVED** [review]

**Pull request merged**
