### PR TITLE
Update OpenAI for new ChatGPT-3.5 fine-tuning release

### PR DESCRIPTION
**Pull request by morganmcg1**
# Changes
- Create new dedicated OpenAI fine-tuning page in Integrations and remove mentions of GPT-3
- Update OpenAI api page in Integrations
- Create new OpenAI page in Prompts docs
  - Given that Prompts is our dedicated place for all thing LLMs it makes sense to highlight other relevant sections of our docs, in this case our OpenAI fine-tuning and API. Once the Prompts LLM Monitoring feature is ready, the OpenAI API docs can be updated to point to it.
- Update sidebar

# Screenshots

## OpenAI Fine-Tuning
Screenshot 2023-08-29 at 15 57 54

Screenshot 2023-08-29 at 15 58 01

Screenshot 2023-08-29 at 15 58 08

Screenshot 2023-08-29 at 15 58 17

Screenshot 2023-08-29 at 15 58 23

Screenshot 2023-08-29 at 15 58 27

## Prompts/OpenAI

Screenshot 2023-08-29 at 16 09 01

### CODE REVIEW

**Comment by ngrayluna** [comment]
This is failing because of the multi language bug. Copy and paste this file in the ja docs (`i18n/ja/docusaurus-plugin-content-docs/current/guides/integrations/`)

**Comment by ngrayluna** [comment]
@morganmcg1 There is a merge conflict. Can you look it over and fix?

**Comment by morganmcg1** [comment]
@ngrayluna could I get a hand with this CI error for a couple of broken links for the JA docs? 

`/ref/python/init` renders for me locally

`/ja/tables/intro` doesn't render for me locally


Its hard to troubleshoot as I'm not sure the JA docs are working for me locally, `http://localhost:3000/ja/guides/integrations` shows "page not found", but I might be using the wrong url?

Screenshot 2023-09-15 at 12 08 26

**Comment by ngrayluna** [comment]
@morganmcg1 Removed old openai.md file from directories did the trick.

**Review by ngrayluna — APPROVED** [review]

**Pull request merged**
